### ISSUE TITLE
Facilitate configuration of RDS & S3 credentials access for Notebooks & Pipelines

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#100]
**Is your feature request related to a problem? Please describe.**
It might not be obvious which k8s secret name to use to create a pod default so that we can use the RDS & S3 credentials setup by the credentials manager. It might not be ovious for new k8s users that you need to create something called a PodDefault in order to have access to these credentials from within a notebook and in notebook creation UI.  
  
**Use Cases**  
- Specify AWS credentials when using `boto3`   
  - Solution : Have a pod default make environment variables available 
- Use `ml-metadata` (requires database credentials in notebook)
  - Solution : Have a pod default make environment variables available

**Describe the solution you'd like**
I propose we add this as part of the Kubeflow install.  
For instance, if the user installs Kubeflow via S3 setup, his pod default could look like 
```yaml
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-aws-secret
  namespace: <YOUR_NAMESPACE_HERE>
  labels:
    add-aws-secret : "true"
spec:
  desc: add-aws-secret
  selector:
    matchLabels:
      add-aws-secret: "true"
  env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: mlpipeline-minio-artifact
        key: accesskey
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: mlpipeline-minio-artifact
        key: secretkey
```
If he installs via RDS & S3 setup then we would add the RDS values (eg: DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PWD from `mysql-secret`) so that the user can [connect to ml metadata db](https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md) in a notebook using OS environment variable values.  
  
This would also open the door to greater notebook integration as we could modify the `spawner_ui_config.yaml` and add the pod default created during the setup as default value selected.  
```yaml
  configurations:
    # List of labels to be selected, these are the labels from PodDefaults
    # value:
    #   - add-gcp-secret
    #   - default-editor
    value:
       - add-aws-secret
    readOnly: false
```
![image](https://user-images.githubusercontent.com/26939775/155630906-0eecf1d9-3fb1-4d01-a85e-1cff46dc37e9.png)
