### ISSUE TITLE
Metadata db is not populated after running a pipeline

### ISSUE THREAD

**Issue by AlexandreBrown** [awslabs/kubeflow-manifests#110]
**Describe the bug**
When using Pipelines integration, if we specify a metadata db name that is different than the Kubeflow default of `metadb` then the metadata like artifacts types will still be pushed to a db named `metadb`.   

**Steps To Reproduce**
1. Specify a name different than `metadb` when setting up the rds db, let's use the db name `kubeflow` for this example
2. Install Kubeflow (tested using `main` branch + manifest `v1.4.1`)
3. Notice how the database `kubeflow` gets created correctly
![image](https://user-images.githubusercontent.com/26939775/156096026-9f5a4d9c-25b3-4170-a462-c310ae408171.png)
![image](https://user-images.githubusercontent.com/26939775/156096072-7d7f0e34-07fa-4984-a121-70ef959196ed.png)
4. Create a pipeline run that pushes some artifacts
Eg: 
```python
@component()
def test_comp(
    value: float,
    model: Output[Model],
    model_metrics: Output[Metrics]
):
    print(f"model_metrics.path {model_metrics.path}")
    print(f"model.path {model.path}")
        
    model_metrics.log_metric("test_loss", value)

    with open(model_metrics.path, 'w') as metrics_file:
        metrics_file.write(str(model_metrics.metadata))
    with open(model.path, 'w') as model_file:
        model_file.write("Some model data")
```
5. Verify that the artifacts metadata was pushed to `kubeflow` db
6. Notice how the db `kubeflow` does not have a new row in `Artifacts`
![image](https://user-images.githubusercontent.com/26939775/156096394-ac025997-752e-4037-96ce-175361848941.png)
7. Verify the table `Artifacts` in `metadb` database instead
![image](https://user-images.githubusercontent.com/26939775/156201882-f8b0635f-8503-48a4-af5e-e1b80fd60768.png)

8. Notice how the metadata was pushed to the `metadb` database instead.  

**Expected behavior**
I expected the metadata to be uploaded to the `kubeflow` db.

**Environment**
* Kubernetes version 1.21
* Using EKS (yes/no), if so version? yes eks.4
* AWS service targeted (S3, RDS, etc.) RDS

**Screenshots**
![image](https://user-images.githubusercontent.com/26939775/156098647-c5098980-7252-44aa-8ace-2c6f7f4e42de.png)

**Additional context**
I could be wrong but I suspect that some changes are required to allow the renaming of the metadata db name.  
If we take a look at `upstream/apps/pipeline/upstream/base/metadata/base/metadata-grpc-deployment.yaml` we see the following :  
```yaml
env:
- name: DBCONFIG_USER
  valueFrom:
    secretKeyRef:
      name: mysql-secret
      key: username
- name: DBCONFIG_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mysql-secret
      key: password
- name: MYSQL_DATABASE
  valueFrom:
    configMapKeyRef:
      name: pipeline-install-config
      key: mlmdDb
- name: MYSQL_HOST
  valueFrom:
    configMapKeyRef:
      name: pipeline-install-config
      key: dbHost
- name: MYSQL_PORT
  valueFrom:
    configMapKeyRef:
      name: pipeline-install-config
      key: dbPort
```  
So it looks like the `MYSQL_DATABASE` is retrieved from `upstream/apps/pipeline/upstream/base/installs/generic/pipeline-install-config.yaml`  
From this config map we can see that the value is hard coded  
```yaml
mlmdDb: metadb
```  
Maybe we'd need to add `mlmdDb` as a param in `awsconfigs/apps/pipeline/params.env` ?
