### ISSUE TITLE
[Doc] Support S3 as source for in Kubeflow Pipelines Artifact Viewer

### ISSUE THREAD

**Issue by akartsky** [awslabs/kubeflow-manifests#117]
"Support S3 Artifact Store" section of document is outdated : https://www.kubeflow.org/docs/distributions/aws/pipeline/#support-s3-artifact-store

## Outdated Doc : 

Kubeflow Pipelines supports different artifact viewers. You can create files in S3 and reference them in output artifacts in your application as follows:

```
metadata = {
        'outputs' : [
          {
              'source': 's3://bucket/kubeflow/README.md',
              'type': 'markdown',
          },
          {
              'type': 'confusion_matrix',
              'format': 'csv',
              'schema': [
                  {'name': 'target', 'type': 'CATEGORY'},
                  {'name': 'predicted', 'type': 'CATEGORY'},
                  {'name': 'count', 'type': 'NUMBER'},
              ],
              'source': s3://bucket/confusion_matrics.csv,
              # Convert vocab to string because for bealean values we want "True|False" to match csv data.
              'labels': list(map(str, vocab)),
          },
          {
              'type': 'tensorboard',
              'source': s3://bucket/tb-events,
          }
        ]
    }

with file_io.FileIO('/tmp/mlpipeline-ui-metadata.json', 'w') as f:
    json.dump(metadata, f)
```

**Comment by mbaijal** [comment]
The current instructions seem to be broken. While we work on a fix using IRSA, the following workaround should help - 

1. Create a secret called `aws-secret` in your user namespace. Make sure to use the AWS_REGION as well as - 
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: <your_kubeflow_user_namespace>
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base_64_key>
  AWS_SECRET_ACCESS_KEY: <base_64_secret>
  AWS_REGION: <region>
```

2. Edit the ml-pipeline-ui-artifact deployment to use the specified secret
`kubectl edit deployment ml-pipeline-ui-artifact -n kubeflow-user-example-com`

3. Once in the vi-editor, add the following changes in the spec.containers section - 
```
spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-secret
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_REGION
              name: aws-secret
```

Now you should be able to create visualizations using artifacts from S3. Also keep the following two points in mind - 
1. Make sure to pass the following parameter to the KFP component's function definition - 
```
mlpipeline_ui_metadata_path: kfp.components.OutputPath()
```
2. and then use it while creating the visualization, something like such - 
```
with open(mlpipeline_ui_metadata_path, 'w') as metadata_file:
        json.dump(metadata, metadata_file)
```
3. And finally, make sure to import and use the following while defining your KFP pipeline - 
```
apply(use_aws_secret('aws-secret', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION'))
```

Do remember this is only a workaround and not a recommendation at the present moment.

**Comment by AlexandreBrown** [comment]
Hello @mbaijal , I'm getting an error when updating the deployment.

```
deployments.apps "ml-pipeline-ui-artifact" was not valid:
 * <nil>: Invalid value: "The edited file failed validation": ValidationError(Deployment.spec.template.spec.containers[0]): missing  
 required field "name" in io.k8s.api.core.v1.Container
```

```yaml
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ml-pipeline-ui-artifact
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ml-pipeline-ui-artifact
    spec:
      containers:
      - env:
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              key: "accesskey"
              name: "mlpipeline-minio-artifact"
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              key: "secretkey"
              name: "mlpipeline-minio-artifact"
        - name: "AWS_REGION"
          value: "us-east-2"
```

**Comment by AlexandreBrown** [comment]
Ok I found the solution, I had to put the env part under the `-image` section for it to work.
```yaml
template:
    metadata:
      creationTimestamp: null
      labels:
        app: ml-pipeline-ui-artifact
    spec:
      containers:
      - image: gcr.io/ml-pipeline/frontend:1.7.0
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-ui-artifact
        env:
        - name: "AWS_ACCESS_KEY_ID"
          valueFrom:
            secretKeyRef:
              key: "accesskey"
              name: "mlpipeline-minio-artifact"
        - name: "AWS_SECRET_ACCESS_KEY"
          valueFrom:
            secretKeyRef:
              key: "secretkey"
              name: "mlpipeline-minio-artifact"
        - name: "AWS_REGION"
          value: "us-east-2"
```
