### ISSUE TITLE
Use secret manager for AWS credentials required for Minio 

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#28]
Possible steps: 
Install secret manager driver: https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html

@
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-2:[111122223333 SOT ISN]:secret:MySecret-00AACC"
          jmesPath: 
              - path: minioAccesskey
                objectAlias: accesskey
              - path: minioSecretKey
                objectAlias: secretKey
```
@rrrkharse
