### ISSUE TITLE
Authentication using OIDC

### ISSUE THREAD

**Issue by rizadiawan** [awslabs/kubeflow-manifests#305]
**What is the URL of the document?**
The URL to help identify the document.
https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide/#dex

**Which section(s) is the issue in?**
The sections(s) within the document that have issue in.
Dex

**What needs fixing and describe the solution you'd like?**
A clear and concise description of what the issue is.
Need guides/examples of setting up authentication with OIDC as alternative to Cognito for managing user authentication.

**Additional context**
Cognito is not supported in some AWS region like Milan, Cape Town, and Jakarta, but sometimes people have to run workload in specific region for regulatory/compliance reason.

**Comment by surajkota** [comment]
Hi @rizadiawan, thanks for creating the issue. For your usecase, there are 2 ways to go about this:
- If you plan to with set up a load balancer, you can directly configure the load balancer to authenticate using [auth-idp-oidc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#auth-idp-oidc) annotation on Ingress or
- [dex connector for OIDC based iDP](https://dexidp.io/docs/connectors/oidc/)

I havent used either of this but have experience configuring Load balancer based authentication. Would you be interested in looking into this? We can guide you based on your idP. If you are okay with using Load balancer, following are the details you will need from your idP to configure it:

1. Issuer Endpoint
2. Authorization Endpoint
3. UserInfo Endpoint
4. Token Endpoint
5. ClientId and Client Secret for your App in idP

I am asking these information based on the following docs:
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#auth-idp-oidc


I expect these information to be used on the ingress like:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: istio-ingress
  annotations:
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"Issuer":"$(oidcIssuer)","AuthorizationEndpoint":"$(oidcAuthorizationEndpoint)","TokenEndpoint":"$(oidcTokenEndpoint)","UserInfoEndpoint":"$(oidcUserInfoEndpoint)","SecretName":"$(oidcSecretName)"}'
    alb.ingress.kubernetes.io/certificate-arn: $(certArn)
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/auth-scope: 'email openid profile'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /*
```

oidcSecretName will be a K8s secret with the ClientId and Client Secret
