### ISSUE TITLE
Access AWS Services from KServe

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#436]
**Is your feature request related to a problem? Please describe.**
Customers want to access AWS services for inference services like pull images for private ECR and download models from S3 bucket.

**Describe the solution you'd like**
Do the above using IRSA

**Comment by surajkota** [comment]
Thành Trần
  [16 hours ago](https://kubeflow.slack.com/archives/CKBA5D0MU/p1663902765436499?thread_ts=1663659424.980629&cid=CKBA5D0MU)
But I have another question: How can I add permission for my model server to pull image from my private registry ?
I am trying to test transformer: https://github.com/kserve/kserve/tree/release-0.7/docs/samples/v1beta1/transformer/torchserve_image_transformer
I build a docker image and push it into my private ECR registry. Then I create a secret (secret-registry) for my private ECR:
```

kubectl create secret docker-registry secret-registry \
--docker-server=80*******03.dkr.ecr.us-east-1.amazonaws.com \
--docker-username=AWS \
--docker-password=$(aws ecr get-login-password --region us-east-1) \
-n staging
```
Then, I create a torch_transformer.yaml file like:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: torchserve-transformer
spec:
  transformer:
    imagePullSecrets:
    - name: secret-registry
    containers:
    - image: 80*********03.dkr.ecr.us-east-1.amazonaws.com/cnndha:image-transformer-v2
      name: kfserving-container
      env:
        - name: STORAGE_URI
          value: gs://kfserving-examples/models/torchserve/image_classifier
  predictor:
    pytorch:
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier
```
Then:
`kubectl apply -n staing -f torch_transformer.yaml`
Is that correct?


Thành Trần
  [16 hours ago](https://kubeflow.slack.com/archives/CKBA5D0MU/p1663902930629519?thread_ts=1663659424.980629&cid=CKBA5D0MU)
seem like still can not pull image from private registry
Can you give me instruction please? I do not find any document about this in kubeflow aws
image.png
 
image.png


Suraj Kota
  [16 minutes ago](https://kubeflow.slack.com/archives/CKBA5D0MU/p1663960340153209?thread_ts=1663659424.980629&cid=CKBA5D0MU)
I would recommend using IAM Role for ServiceAccount (IRSA) approach to pull images from private ECR.
They token you are trying put in the secret will expire and if the isvc scales on a different node, it will fail to pull the image again (edited) 


Suraj Kota
  [8 minutes ago](https://kubeflow.slack.com/archives/CKBA5D0MU/p1663960838367419?thread_ts=1663659424.980629&cid=CKBA5D0MU)
Create a policy with following [permissions](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html):
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken"
            ],
            "Resource": "*"
        }
    ]
}
```
2. Create a IAM role and attach it to a service account using [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)
`eksctl create iamserviceaccount --name image-pull-sa --namespace ${YOUR_PROFILE_NAMESPACE} --cluster ${CLUSTER_NAME} --region ${CLUSTER_REGION} --attach-policy-arn ${IAM_POLICY_ARN} --override-existing-serviceaccounts --approve`
3. Specify this service account in the transformer spec
```
spec:
  transformer:
    serviceAccountName: image-pull-sa

```
docs.aws.amazon.comdocs.aws.amazon.com
[IAM roles for service accounts - Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)
Learn how applications in your pods can access AWS services.
