### ISSUE TITLE
Remove IAM user usage in Kubeflow and replace that with IAM role

### ISSUE THREAD

**Issue by goswamig** [awslabs/kubeflow-manifests#44]
We want kubeflow to be completely off the usage of static credentials but only using IRSA. 
1. figure out the IAM user usage in kubeflow component. 
2. Replace them with IAM role using IRSA.

**Comment by revolutionisme** [comment]
@goswamig Is there any update on this? IIRC, we could use IRSA for setting up kubeflow pipelines separately but this seems to be not possible with Kubeflow and this is a critical requirement for us as we are restricted to creating static users on our AWS accounts!

**Comment by icereed** [comment]
This is a very important feature to us since static IAM users are a security issue because the credentials can leak.
Highly appreciated if this is being worked on. 👍

**Comment by muthurajr** [comment]
@revolutionisme @icereed A patch for the minio deployment using s3 gateway can be applied as a temporary solution.

An example,

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      serviceAccountName: minio
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-02-01T18-00-14Z
          args:
            - gateway
            - s3
          volumeMounts:
          - name: data
            $patch: delete
      volumes:
        - name: data
          $patch: delete
 ```

Here "minio" is a eks service account with IAM role attached, and container image needs update as well.
