### ISSUE TITLE
cert-manager webhooks fails with reason `FailedDiscoveryCheck`

### ISSUE THREAD

**Issue by pthalasta** [awslabs/kubeflow-manifests#457]
cert-manager installed with kubeflow fails with the following error

```sh
status:
  conditions:
  - lastTransitionTime: "2022-06-30T19:18:55Z"
    message: 'failing or missing response from https://<ip>:10251/apis/webhook.cert-manager.io/v1beta1:
      bad status from https://<ip>:10251/apis/webhook.cert-manager.io/v1beta1:
      404'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```

pods in cert-manager namespace:

```sh
kc get pods -n cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-66b646d76-8bz6r               1/1     Running   0          99d
cert-manager-cainjector-59dc9659c7-7r66d   1/1     Running   0          99d
cert-manager-webhook-7fbcc4bfcb-6kgm6      1/1     Running   0          99d
```

webhook deployment yaml from kubeflow manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: "cert-manager"
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.5.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: "webhook"
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/name: webhook
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/component: "webhook"
        app.kubernetes.io/version: "v1.5.0"
    spec:
      serviceAccountName: cert-manager-webhook
      securityContext:
        runAsNonRoot: true
      hostNetwork: true
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-webhook:v1.5.0"
          imagePullPolicy: IfNotPresent
          args:
          - --v=2
          - --secure-port=10251
          - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
          - --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
          - --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
          ports:
          - name: https
            protocol: TCP
            containerPort: 10251
          livenessProbe:
            httpGet:
              path: /livez
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {}
```
**Expected behavior**
webhook should Pass the discovery check

**Environment**
* Kubernetes version: 1.20
* Using EKS (yes/no), if so version? yes, 1.20
* Kubeflow version 1.5
* AWS build number: This was installed through kubeflow manifests from kubeflow repo with kustomize
* AWS service targeted (S3, RDS, etc.)

While looking for the solution online i found some other having similar issue on GKE resolve it with firewall changes
https://github.com/cert-manager/cert-manager/issues/2109#issuecomment-535901422 not sure if this required with EKS as the installation instructions i followed was from kubeflow than using awslabs's kubeflow manifests? Any help in resolving this would be really helpful!
