### ISSUE TITLE
URL/authservice is not exposed in istio via virtualservice for oidc-authservice

### ISSUE THREAD

**Issue by omidrk** [awslabs/kubeflow-manifests#702]
**Describe the bug**
In the Kubeflow 1.7 helm charts, oidc-authservice is using /authservice prefix which is not exposed via virtualservice. As a result URL/authservice is not accessible for Dex as a redirect URL . 
Dex config map in helm chart:
```
    staticClients:
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/authservice/oidc/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
```
This will cause Dex to not return to oidc-authservice after the login and will show empty page.

**Environment**
* Kubernetes version 1.24
* Using EKS (yes/no), if so version? Yes
* Kubeflow version 1.7
