### ISSUE TITLE
Knative queue-proxy - no metrics on port 9090

### ISSUE THREAD

**Issue by tikr7** [awslabs/kubeflow-manifests#747]
**Describe the bug**
Knative queue-proxy gives no metrics on port 9090 (important for rps and concurrency metrics to autoscale accordingly).
Is it a AWS kubeflow specific bug? Or has something changed from kubeflow version 1.6 to 1.7 I am not aware of?

**Steps To Reproduce**
0. I did a fresh install of kubeflow on AWS using version: "v1.7.0-aws-b1.0.1" with "rds-s3" (I used terraform)

1. Create a simple ksvc:
```
cat <<EOF | kubectl apply -f -
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: nginx:1.14.2
          ports:
            - containerPort: 80
EOF
```
2. Do a simple portforwarding on that pod (you can also go over the svc - same results)
```
kubectl get pod
nginx-00001-deployment-b567b5f57-hkw2k

kubectl port-forward -n default pod/nginx-00001-deployment-b567b5f57-hkw2k 9090:9090
```
3. Either do `curl http://localhost:9090/metrics` or open it in a browser: `http://localhost:9090/metrics`. It does not show the metrics.
Btw: the same works on port 9091...

**Expected behavior**
It should show rps and concurrency metrics similar to port 9091. To see how the metrics look on port 9091, simply do:
```
kubectl port-forward -n default pod/nginx-00001-deployment-b567b5f57-hkw2k 9091:9091
curl http://localhost:9091/metrics
```

**Environment**
"v1.7.0-aws-b1.0.1" with "rds-s3" should answer everything
* Kubernetes version: v1.25.9-eks-0a21954
* Using EKS (yes/no), if so version? Yes, v1.25.9-eks-0a21954
* Kubeflow version, 1.7
* AWS build number: ?
* AWS service targeted (S3, RDS, etc.): rds+s3
