### ISSUE TITLE
Memory limit issue occurs when provisioning nodes by Karpenter

### ISSUE THREAD

**Issue by HanHoRang31** [awslabs/kubeflow-manifests#748]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**
I'm testing by integrating karpenter and kubeflow. When kubeflow requests to create a notebook using gpu, I want to create a gpu node(p2.xlarge) in the registered carpenter and have the notebook pod deploy to the gpu node 

However, when deploying the pod, the number of memory changes non-ideally, so it cannot be deployed to the node. What's the problem? The memory limit becomes non-ideal, even if the memory limit is measured as '2' in kubeflow, the memory limit value changes strangely when a pod is deployed on a node. 

**Environment**
* Kubernetes version 1.24
* Using EKS (yes/no), if so version? yes
* Kubeflow version 1.17
* AWS build number 
* AWS service targeted (S3, RDS, etc.)

**Screenshots**

<img width="1003" alt="kar6" src="https://github.com/awslabs/kubeflow-manifests/assets/117359361/8ebd77fc-2359-4053-9f25-2d0e787a204e">
<img width="952" alt="kar5" src="https://github.com/awslabs/kubeflow-manifests/assets/117359361/b39e1bc0-abb4-449b-9bc0-3ba96b037772">
<img width="1009" alt="kar4" src="https://github.com/awslabs/kubeflow-manifests/assets/117359361/619b5c68-569f-496a-953d-60e749111578">

**Additional context**

**Comment by HanHoRang31** [comment]
The answer was late. I'll share the Karpenter provisioning value.

```
cat <<EOF | kubectl apply -f -
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: ${CLUSTER_NAME}
  securityGroupSelector:
    karpenter.sh/discovery: ${CLUSTER_NAME}
EOF
```

I had the same problem when I expanded the capacity.
 It seems to me that when creating a GPU Pod inside KUBEFLOW, we should see that the request limit value is abnormally large.
<img width="1003" alt="kar6" src="https://github.com/awslabs/kubeflow-manifests/assets/117359361/02bd86f7-64e9-4dc9-8ee5-d8954e1b2e52">
