### ISSUE TITLE
[Component Guide] KFServing

### ISSUE THREAD

**Issue by surajkota** [awslabs/kubeflow-manifests#82]
**Is your feature request related to a problem? Please describe.**
Existing samples/tutorial in this repository focus on how to install Kubeflow on EKS.
[kserve docs](https://kserve.github.io/website/0.7/get_started/first_isvc/) show how to create an inference service and sending requests from ingress gateway, if user has a realDNS etc. It does not talk about auth or how to setup a real DNS

**Describe the solution you'd like**
- [x] E2e tutorials for users on how to use inference service in production on AWS with an ALB endpoint/custom domain and auth
- [ ] How to use a model in S3

**Comment by surajkota** [comment]
Working e2e POC:

In this tutorial we will create a TLS enabled load balancer endpoint for serving prediction requests over HTTPS.

Pre-requisites:
1. Kubeflow deployment
2. Alb ingress controller installed
3. Cluster subnets tagged according to the `Prerequisites` section in this [document](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) for ALB controller to work

Background:
- Currently, it is not possible to programatically authenticate a request through ALB that is using cognito authentication.
- Certificates for ALB public DNS names are not supported. Instead, you must create a custom domain.

Hence, we will be creating another ALB endpoint which authorizes based on a token in a predefined header.

Step 1: Register a domain or reuse the domain if you are using the Cognito based deployment. You can get a domain using any domain registration service like [Route53](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html) or godaddy.com

Step 2: Modify [knative domain configuration to use your custom domain](https://knative.dev/docs/serving/using-a-custom-domain/). **Note** that knative default domain is in the format `{route}.{namespace}.{default-domain}`. Lets assume your domain name is `platform.example.com` and you will create the resource in `kserve` namespace. We will use this information in the next step

Step 3: To get TLS support from the ALB, you need to request a certificate in AWS Certificate Manager. Follow [this tutorial](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html) to create a certificate for `*.example.com` and `*.kserve.example.com`(both domains in the same certificate) in the region where your cluster exists.
After successful validation, you will get a certificate ARN to use with the Ingress ALB endpoint. 

Step 4: Create an ingress with the following config by substituting the value of `randomStringxxx` and `randomStringyyy`. You can also change the HttpHeaderName from `x-api-key` to your choice of header.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=180
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:ca-central-1:123456789012:certificate/xxxxxx-xxxx-xxxx-xxxx-xxxxxxx'
    alb.ingress.kubernetes.io/conditions.istio-ingressgateway: '[{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "x-api-key", "Values":["randomStringxxx", "randomStringyyy"]}}]'
    alb.ingress.kubernetes.io/actions.istio-ingressgateway: '{"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"istio-ingressgateway","ServicePort":"80","Weight":100}]}}'
    kubernetes.io/ingress.class: alb
  name: istio-ingress-api
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
        path: /*
```

Step 5: Wait for the ALB to get created (this takes about 3-5 minutes)
```
$ kubectl get ingress -n istio-system istio-ingress-api
NAME            CLASS    HOSTS   ADDRESS                                                                     PORTS   AGE
istio-ingress   <none>   *       956f2953-istiosystem-istio-2gh2-1234567890.ca-central-1.elb.amazonaws.com   80      14m
```

Step 6: When ALB is ready, copy the DNS name of that load balancer and create a CNAME entries to it in Route53 under subdomain (`platform.example.com`) for `*.platform.example.com` and `*.kserve.platform.example.com`.

Step 7: Create a sample sklearn InferenceService and wait for it to be READY
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: kserve
spec:
  predictor:
    sklearn:
      storageUri: "gs://kfserving-samples/models/sklearn/iris"
```

```
$ k get inferenceservice -A
NAMESPACE    NAME           URL                                                  READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                    AGE
kserve       sklearn-iris   http://sklearn-iris.kserve.platform.example.com       True           100                              sklearn-iris-predictor-default-00001   2d
```

Step 8: Your endpoint is ready to serve! Send request using the sample script below:
```
import requests

data = {
  "instances": [
    [6.8,  2.8,  4.8,  1.4],
    [6.0,  3.4,  4.5,  1.6]
  ]
}

url = "https://sklearn-iris.kserve.platform9.surakota.people.aws.dev/v1/models/sklearn-iris:predict"
headers = {
  "Host" : "sklearn-iris.kserve.platform9.surakota.people.aws.dev",
  "x-api-key": "randomStringxxx"
}

response = requests.post(url, headers=headers, json=data)

print("Status Code", response.status_code)
print("JSON Response ", response.json())
```

Output would look like:
```
Status Code 200
JSON Response  {'predictions': [1, 1]}
```

**Comment by ryansteakley** [comment]
Looks fine to me, in the pre-requisites when you direct them towards https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html to have the cluster subnets tagged properly, perhaps we should also link to this command we have in the cognito readme to make it easier for the user? Specifically section 4 of this https://github.com/awslabs/kubeflow-manifests/tree/main/docs/deployment/cognito#40-configure-ingress

**Comment by surajkota** [comment]
for 1. -> I will work on #67 first so the prerequisites are reduced
2 -> tokens are static strings. They are not linked to any session and hence have no expiration times. Will add this to the documentation or think of a better wording

**Comment by AlexandreBrown** [comment]
@surajkota I see that we specify 2 values for the tokens when defining the Ingress but we only specify one when doing a test request.  
Should we use 1 or 2 values?

**Comment by AlexandreBrown** [comment]
Hello, we followed the guide but unfortunately could not get an inference to return a result.   

# Important of the issue
**This issue is critical for us since it blocks us from deploying any model to production.**  
  
# Issue  
Performing an inference to a model server returns a 504 Gateway Timeout Error   

# Steps to reproduce  
1. Create a cluster on EKS 1.21
Here is the cluster definition I used 
```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster-1
  version: "1.21"
  region: us-east-2

availabilityZones: ["us-east-2a", "us-east-2b"]

managedNodeGroups:
  - name: ai-platform-1
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    instanceType: m6i.xlarge
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/mycluster-1: "owned"
```
2. Install Kubeflow according to RDS-S3-Cognito setup (I used the rds-s3 script for rds-s3 part then manually did Cognito following the doc)
- Branch : `main` + `upstream v1.4.1`
3. Create a profile/namespace `prod`
```yaml
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: prod
```
4. Create a `default-editor` service account for `prod`
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-editor-access-binding-prod
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: prod
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  ``` 
5. Authorize yourself to the namespace (follow [kuveflow doc step](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually) )
6. Setup KFServing
7. Perform an inference.
8. Notice 504 error
# Context
- Cluster region : us-east-2
- Cognito setup
  - Root domain (`mydomain.com`) is under [a different domain registry](https://www.namecheap.com/) (not AWS Route53)
    - I created a [Hosted Zone](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-working-with.html) for the subdomain `ai.mydomain.com` to allow subdomain delegation.
    - I created 4 `NS` records on my root domain registry with the nameservers from the subdomain hosted zone
  ![image](https://user-images.githubusercontent.com/26939775/158459053-6241fe4c-3942-4e37-95c5-3f40c59fa4c6.png)
- KFServing setup 
  - Modified the config-domain config map to use my sub domain.  
    - `kubectl edit configmap config-domain -n knative-serving`
```yaml
apiVersion: v1
data:
  ai.mydomain.com: ""
kind: ConfigMap
[...]
```
  - Certificates
    - I successfully created a certificate in **us-east-2 (my cluster region)** using [AWS Certificate Manager](https://us-east-2.console.aws.amazon.com/acm/home?region=us-east-2#/welcome).  
      - The certificate has 2 domain values :  `*.prod.ai.mydomain.com` and `*.ai.mydomain.com`
  -  Created the ingress using a copy paste from the procedure and I entered the certificate ARN in place of `arn:aws:acm:ca-central-1:123456789012:certificate/xxxxxx-xxxx-xxxx-xxxx-xxxxxxx`
  - Created a CNAME for the ELB
```
*.prod.ai.mydomain.com | CNAME | Simple | - | 0dfceb22-istiosystem-istio-a50d-1499903191.us-east-2.elb.amazonaws.com
```  
  
Any help on this would be extremely appreciated.

**Comment by surajkota** [comment]
Thanks for reporting the issue and detailed steps to reproduce. My first thought is you might be hitting these open issue where auth policy is incomplete in profile namespace: https://github.com/kserve/kserve/issues/1558, https://github.com/kubeflow/kubeflow/issues/5965. I can confirm this issue exists in 1.4 since I was also not able to get the request served in profile namespace.

I created a plain k8s namespace using: `kubectl create namespace kserve`. Can you try this as well?

I understand from our discussion that this is not ideal since these models wont be visible in the webapp and it will not be accessible from pipelines or notebooks but lets try to break this into: getting inference request served w/o profile and getting it to work in profile namespace

**Comment by AlexandreBrown** [comment]
Thank you @surajkota , I was able to still use profiles by applying the right auth policy (mine is slightly modified to the one linked to add v2 protocol support) :  
```yaml  
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-predictor
  namespace: istio-system
spec:
  selector:
    matchLabels:
      component: predictor
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics
        - /healthz
        - /ready
        - /wait-for-drain
        - /v1/models/*
        - /v2/models/*
```  
If someone uses transformers he would need to apply it for transformers as well :   
```yaml  
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-transformer
  namespace: istio-system
spec:
  selector:
    matchLabels:
      component: transformer
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /metrics
        - /healthz
        - /ready
        - /wait-for-drain
        - /v1/models/*
        - /v2/models/*
```  
  
This is not an AWS issue, it should be added to vanilla Kubeflow in my opinion.  
Until it is added to vanilla Kubeflow we could mention it in the doc so that people with KF 1.4 don't face the issue.
